export const SET_FEEDINGS = "SET_FEEDINGS";
export const GET_FEEDING = "GET_FEEDING";

export const SET_SLEEPS = "SET_SLEEPs";
export const GET_SLEEP = "GET_SLEEP";

export const SET_POTTIES = "SET_POTTIES";
export const GET_POTTY = "GET_POTTY";

export const FETCHING_STARTED = "FETCHING_STARTED";
export const FETCHING_DONE = "FETCHING_DONE";

export const NEW_FEEDING_SAVE_FAILED = "NEW_FEEDING_SAVE_FAILED";
export const NEW_FEEDING_SAVE_SUCCEEDED = "NEW_FEEDING_SAVE_SUCCEEDED";
export const NEW_FEEDING_SAVE_STARTED = "NEW_FEEDING_SAVE_STARTED";
export const NEW_FEEDING_FORM_UPDATED = "NEW_FEEDING_FORM_UPDATED";
export const NEW_FEEDING_CLEARED = "NEW_FEEDING_CLEARED";

export const NEW_SLEEP_SAVE_FAILED = "NEW_SLEEP_SAVE_FAILED";
export const NEW_SLEEP_SAVE_SUCCEEDED = "NEW_SLEEP_SAVE_SUCCEEDED";
export const NEW_SLEEP_SAVE_STARTED = "NEW_SLEEP_SAVE_STARTED";
export const NEW_SLEEP_FORM_UPDATED = "NEW_SLEEP_FORM_UPDATED";
export const NEW_SLEEP_CLEARED = "NEW_SLEEP_CLEARED";

export const NEW_POTTY_SAVE_FAILED = "NEW_POTTY_SAVE_FAILED";
export const NEW_POTTY_SAVE_SUCCEEDED = "NEW_POTTY_SAVE_SUCCEEDED";
export const NEW_POTTY_SAVE_STARTED = "NEW_POTTY_SAVE_STARTED";
export const NEW_POTTY_FORM_UPDATED = "NEW_POTTY_FORM_UPDATED";
export const NEW_POTTY_CLEARED = "NEW_POTTY_CLEARED";
